version: '3'

services:
  mysql-docker-container:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    ports:
    - 3306:3306
    volumes:
      - /data/mysql
  sesame-appointment-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/sesame-appointment
